import { v4 as uuid } from "uuid";
import {
  atomic,
  goneGirl,
  fiveAm,
  devotionOfSuspect,
  alchemist,
  defenderInChief,
  inColdBlood,
  greatGatsby,
} from "../../assets";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: devotionOfSuspect,
    title: "The Devotion of Suspect X",
    author: "Keigo Higashino",
    discountPrice: "343",
    originalPrice: "499",
    discountPercent: "31",
    rating: 3.2,
    categoryName: "Fiction",
  },
  {
    _id: uuid(),
    img: atomic,
    title: "Atomic Habits",
    author: "James Clear",
    discountPrice: "599",
    originalPrice: "999",
    discountPercent: "40",
    rating: 2.5,
    categoryName: "Self help",
  },
  {
    _id: uuid(),
    img: fiveAm,
    title: "The 5 AM Club",
    author: "Robin Sharma",
    discountPrice: "799",
    originalPrice: "999",
    discountPercent: "30",
    rating: 1.9,
    categoryName: "Self help",
  },
  {
    _id: uuid(),
    img: goneGirl,
    title: "Gone girl",
    author: "Gillian Flynn",
    discountPrice: "699",
    originalPrice: "799",
    discountPercent: "10",
    rating: 5,
    categoryName: "Fiction",
  },
  {
    _id: uuid(),
    img: alchemist,
    title: "The Alchemist",
    author: "Paulo Coelho",
    discountPrice: "253",
    originalPrice: "350",
    discountPercent: "28",
    rating: 4.5,
    categoryName: "Fiction",
  },
  {
    _id: uuid(),
    img: defenderInChief,
    title: "Defender in Chief",
    author: "John Yoo",
    discountPrice: "798",
    originalPrice: "999",
    discountPercent: "20",
    rating: 3.8,
    categoryName: "Non-fiction",
  },
  {
    _id: uuid(),
    img: inColdBlood,
    title: "In Cold Blood",
    author: "Truman Capote",
    discountPrice: "899",
    originalPrice: "999",
    discountPercent: "10",
    rating: 4.1,
    categoryName: "Non-fiction",
  },
  {
    _id: uuid(),
    img: greatGatsby,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    discountPrice: "109",
    originalPrice: "399",
    discountPercent: "72%",
    rating: 4.4,
    categoryName: "Fiction",
  },
];
