const INITIAL_ACTIONS = {
  INITIALIZE_CATEGORIES: "INITIALIZE_CATEGORIES",
  INITIALIZE_PRODUCTS: "INITIALIZE_PRODUCTS",
};
const FILTER_ACTIONS = {
  CLEAR_ALL: " CLEAR_ALL",
  HIGH_TO_LOW: "HIGH_TO_LOW",
  LOW_TO_HIGH: "LOW_TO_HIGH",
  PRICE_RANGE: "PRICE_RANGE",
  RATING: "RATING",
  CHANGE_CATEGORY: "CHANGE_CATEGORY",
};
const PRODUCT_ACTIONS = {
  ADD_TO_CART: "ADD_TO_CART",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  UPDATE_WISHLIST:"UPDATE_WISHLIST",
  UPDATE_CART:"UPDATE_CART",
  INCREASE_QTY: "INCREASE_QTY",
  DECREASE_QTY: "DECREASE_QTY",
};
const USER_ACTIONS={
  LOGOUT:"LOGOUT",
  CLEAR_CART:"CLEAR_CART",
}
export { INITIAL_ACTIONS, FILTER_ACTIONS, PRODUCT_ACTIONS,USER_ACTIONS };
