const INITIAL_ACTIONS = {
  INITIALIZE_CATEGORIES: "INITIALIZE_CATEGORIES",
  INITIALIZE_PRODUCTS: "INITIALIZE_PRODUCTS",
};
const FILTER_ACTIONS = {
  CLEAR_ALL: " CLEAR_ALL",
  HIGH_TO_LOW: "HIGH_TO_LOW",
  LOW_TO_HIGH: "LOW_TO_HIGH",
  PRICE_RANGE: "PRICE_RANGE",
  RATING: "RATING",
  CHANGE_CATEGORY: "CHANGE_CATEGORY",
};
export { INITIAL_ACTIONS, FILTER_ACTIONS };
